# Generated by Django 4.0.3 on 2022-06-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='chatroom',
        ),
    ]
