# Generated by Django 4.0.3 on 2022-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatrooms',
            field=models.ManyToManyField(related_name='rooms', to='chat.chatroom'),
        ),
    ]
